
package knowyourtown.business.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import knowyourtown.localdb.webservice.Person;
import knowyourtown.localdb.webservice.Place;
import knowyourtown.localdb.webservice.Suggestion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Business", targetNamespace = "http://webservice.business.knowyourtown/")
@XmlSeeAlso({
    knowyourtown.localdb.webservice.ObjectFactory.class,
    knowyourtown.business.webservice.ObjectFactory.class
})
public interface Business {


    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.CreatePersonResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/createPersonRequest", output = "http://webservice.business.knowyourtown/Business/createPersonResponse")
    public int createPerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.business.knowyourtown/")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.UpdatePersonResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/updatePersonRequest", output = "http://webservice.business.knowyourtown/Business/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.business.knowyourtown/")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeletePersonResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/deletePersonRequest", output = "http://webservice.business.knowyourtown/Business/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personId
     * @param place
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "placeId", targetNamespace = "")
    @RequestWrapper(localName = "createPlace", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.CreatePlace")
    @ResponseWrapper(localName = "createPlaceResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.CreatePlaceResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/createPlaceRequest", output = "http://webservice.business.knowyourtown/Business/createPlaceResponse")
    public int createPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "place", targetNamespace = "http://webservice.business.knowyourtown/")
        Place place);

    /**
     * 
     * @param personId
     * @param place
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "placeId", targetNamespace = "")
    @RequestWrapper(localName = "updatePlace", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.UpdatePlace")
    @ResponseWrapper(localName = "updatePlaceResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.UpdatePlaceResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/updatePlaceRequest", output = "http://webservice.business.knowyourtown/Business/updatePlaceResponse")
    public int updatePlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "place", targetNamespace = "http://webservice.business.knowyourtown/")
        Place place);

    /**
     * 
     * @param placeId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePlace", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeletePlace")
    @ResponseWrapper(localName = "deletePlaceResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeletePlaceResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/deletePlaceRequest", output = "http://webservice.business.knowyourtown/Business/deletePlaceResponse")
    public int deletePlace(
        @WebParam(name = "placeId", targetNamespace = "")
        int placeId);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Suggestion>
     */
    @WebMethod
    @WebResult(name = "listSuggestion", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestions", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.GetSuggestions")
    @ResponseWrapper(localName = "getSuggestionsResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.GetSuggestionsResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/getSuggestionsRequest", output = "http://webservice.business.knowyourtown/Business/getSuggestionsResponse")
    public List<Suggestion> getSuggestions(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param suggestion
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "suggestionId", targetNamespace = "")
    @RequestWrapper(localName = "createSuggestion", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.CreateSuggestion")
    @ResponseWrapper(localName = "createSuggestionResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.CreateSuggestionResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/createSuggestionRequest", output = "http://webservice.business.knowyourtown/Business/createSuggestionResponse")
    public int createSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "suggestion", targetNamespace = "http://webservice.business.knowyourtown/")
        Suggestion suggestion);

    /**
     * 
     * @param suggestion
     * @param oldTitle
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "suggestionId", targetNamespace = "")
    @RequestWrapper(localName = "updateSuggestion", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.UpdateSuggestion")
    @ResponseWrapper(localName = "updateSuggestionResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.UpdateSuggestionResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/updateSuggestionRequest", output = "http://webservice.business.knowyourtown/Business/updateSuggestionResponse")
    public int updateSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "suggestion", targetNamespace = "http://webservice.business.knowyourtown/")
        Suggestion suggestion,
        @WebParam(name = "oldTitle", targetNamespace = "")
        String oldTitle);

    /**
     * 
     * @param suggestionId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteSuggestion", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeleteSuggestion")
    @ResponseWrapper(localName = "deleteSuggestionResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeleteSuggestionResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/deleteSuggestionRequest", output = "http://webservice.business.knowyourtown/Business/deleteSuggestionResponse")
    public int deleteSuggestion(
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId);

    /**
     * 
     * @param suggestionId
     * @param title
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteSuggestionByTitle", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeleteSuggestionByTitle")
    @ResponseWrapper(localName = "deleteSuggestionByTitleResponse", targetNamespace = "http://webservice.business.knowyourtown/", className = "knowyourtown.business.webservice.DeleteSuggestionByTitleResponse")
    @Action(input = "http://webservice.business.knowyourtown/Business/deleteSuggestionByTitleRequest", output = "http://webservice.business.knowyourtown/Business/deleteSuggestionByTitleResponse")
    public int deleteSuggestionByTitle(
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId,
        @WebParam(name = "title", targetNamespace = "")
        String title);

}
