
package knowyourtown.storage.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import knowyourtown.localdb.webservice.Person;
import knowyourtown.localdb.webservice.Place;
import knowyourtown.localdb.webservice.PlaceType;
import knowyourtown.localdb.webservice.Suggestion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Storage", targetNamespace = "http://webservice.storage.knowyourtown/")
@XmlSeeAlso({
    knowyourtown.localdb.webservice.ObjectFactory.class,
    knowyourtown.storage.webservice.ObjectFactory.class
})
public interface Storage {


    /**
     * 
     * @param personId
     * @return
     *     returns knowyourtown.localdb.webservice.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadPersonResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/readPersonRequest", output = "http://webservice.storage.knowyourtown/Storage/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.CreatePersonResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/createPersonRequest", output = "http://webservice.storage.knowyourtown/Storage/createPersonResponse")
    public int createPerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.storage.knowyourtown/")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.UpdatePersonResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/updatePersonRequest", output = "http://webservice.storage.knowyourtown/Storage/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.storage.knowyourtown/")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.DeletePersonResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/deletePersonRequest", output = "http://webservice.storage.knowyourtown/Storage/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param placeId
     * @param personId
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.Place
     */
    @WebMethod
    @WebResult(name = "place", targetNamespace = "")
    @RequestWrapper(localName = "readPlace", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadPlace")
    @ResponseWrapper(localName = "readPlaceResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadPlaceResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/readPlaceRequest", output = "http://webservice.storage.knowyourtown/Storage/readPlaceResponse")
    public Place readPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId,
        @WebParam(name = "placeId", targetNamespace = "")
        int placeId);

    /**
     * 
     * @param personId
     * @param placeTypeId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Place>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "getPlaceHistory", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetPlaceHistory")
    @ResponseWrapper(localName = "getPlaceHistoryResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetPlaceHistoryResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getPlaceHistoryRequest", output = "http://webservice.storage.knowyourtown/Storage/getPlaceHistoryResponse")
    public List<Place> getPlaceHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId);

    /**
     * 
     * @param nPlace
     * @param personId
     * @param placeTypeId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Place>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "getSomePlace", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSomePlace")
    @ResponseWrapper(localName = "getSomePlaceResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSomePlaceResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getSomePlaceRequest", output = "http://webservice.storage.knowyourtown/Storage/getSomePlaceResponse")
    public List<Place> getSomePlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId,
        @WebParam(name = "nPlace", targetNamespace = "")
        int nPlace);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Place>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "getLastPlace", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetLastPlace")
    @ResponseWrapper(localName = "getLastPlaceResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetLastPlaceResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getLastPlaceRequest", output = "http://webservice.storage.knowyourtown/Storage/getLastPlaceResponse")
    public List<Place> getLastPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personId
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.Place
     */
    @WebMethod
    @WebResult(name = "place", targetNamespace = "")
    @RequestWrapper(localName = "getLastPlaceByType", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetLastPlaceByType")
    @ResponseWrapper(localName = "getLastPlaceByTypeResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetLastPlaceByTypeResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getLastPlaceByTypeRequest", output = "http://webservice.storage.knowyourtown/Storage/getLastPlaceByTypeResponse")
    public Place getLastPlaceByType(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId);

    /**
     * 
     * @param personId
     * @param place
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "placeId", targetNamespace = "")
    @RequestWrapper(localName = "createPlace", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.CreatePlace")
    @ResponseWrapper(localName = "createPlaceResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.CreatePlaceResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/createPlaceRequest", output = "http://webservice.storage.knowyourtown/Storage/createPlaceResponse")
    public int createPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "place", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Place place);

    /**
     * 
     * @param personId
     * @param place
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "placeId", targetNamespace = "")
    @RequestWrapper(localName = "updatePlace", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.UpdatePlace")
    @ResponseWrapper(localName = "updatePlaceResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.UpdatePlaceResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/updatePlaceRequest", output = "http://webservice.storage.knowyourtown/Storage/updatePlaceResponse")
    public int updatePlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "place", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Place place);

    /**
     * 
     * @param placeId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePlace", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.DeletePlace")
    @ResponseWrapper(localName = "deletePlaceResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.DeletePlaceResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/deletePlaceRequest", output = "http://webservice.storage.knowyourtown/Storage/deletePlaceResponse")
    public int deletePlace(
        @WebParam(name = "placeId", targetNamespace = "")
        int placeId);

    /**
     * 
     * @param suggestionId
     * @return
     *     returns knowyourtown.localdb.webservice.PlaceType
     */
    @WebMethod
    @WebResult(name = "placeType", targetNamespace = "")
    @RequestWrapper(localName = "readPlaceType", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadPlaceType")
    @ResponseWrapper(localName = "readPlaceTypeResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadPlaceTypeResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/readPlaceTypeRequest", output = "http://webservice.storage.knowyourtown/Storage/readPlaceTypeResponse")
    public PlaceType readPlaceType(
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId);

    /**
     * 
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.PlaceType>
     */
    @WebMethod
    @WebResult(name = "placeTypeList", targetNamespace = "")
    @RequestWrapper(localName = "getPlaceTypeList", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetPlaceTypeList")
    @ResponseWrapper(localName = "getPlaceTypeListResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetPlaceTypeListResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getPlaceTypeListRequest", output = "http://webservice.storage.knowyourtown/Storage/getPlaceTypeListResponse")
    public List<PlaceType> getPlaceTypeList();

    /**
     * 
     * @param type
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idPlaceType", targetNamespace = "")
    @RequestWrapper(localName = "getIdPlaceTypeByType", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetIdPlaceTypeByType")
    @ResponseWrapper(localName = "getIdPlaceTypeByTypeResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetIdPlaceTypeByTypeResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getIdPlaceTypeByTypeRequest", output = "http://webservice.storage.knowyourtown/Storage/getIdPlaceTypeByTypeResponse")
    public int getIdPlaceTypeByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Suggestion>
     */
    @WebMethod
    @WebResult(name = "suggestionList", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestions", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSuggestions")
    @ResponseWrapper(localName = "getSuggestionsResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSuggestionsResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getSuggestionsRequest", output = "http://webservice.storage.knowyourtown/Storage/getSuggestionsResponse")
    public List<Suggestion> getSuggestions(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param suggestionId
     * @param personId
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.Suggestion
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "")
    @RequestWrapper(localName = "readSuggestion", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadSuggestion")
    @ResponseWrapper(localName = "readSuggestionResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.ReadSuggestionResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/readSuggestionRequest", output = "http://webservice.storage.knowyourtown/Storage/readSuggestionResponse")
    public Suggestion readSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId,
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId);

    /**
     * 
     * @param personId
     * @param placeTypeId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Suggestion>
     */
    @WebMethod
    @WebResult(name = "suggestionList", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestionHistory", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSuggestionHistory")
    @ResponseWrapper(localName = "getSuggestionHistoryResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSuggestionHistoryResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getSuggestionHistoryRequest", output = "http://webservice.storage.knowyourtown/Storage/getSuggestionHistoryResponse")
    public List<Suggestion> getSuggestionHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId);

    /**
     * 
     * @param suggestion
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "suggestionId", targetNamespace = "")
    @RequestWrapper(localName = "createSuggestion", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.CreateSuggestion")
    @ResponseWrapper(localName = "createSuggestionResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.CreateSuggestionResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/createSuggestionRequest", output = "http://webservice.storage.knowyourtown/Storage/createSuggestionResponse")
    public int createSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "suggestion", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Suggestion suggestion);

    /**
     * 
     * @param suggestion
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "suggestionId", targetNamespace = "")
    @RequestWrapper(localName = "updateSuggestion", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.UpdateSuggestion")
    @ResponseWrapper(localName = "updateSuggestionResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.UpdateSuggestionResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/updateSuggestionRequest", output = "http://webservice.storage.knowyourtown/Storage/updateSuggestionResponse")
    public int updateSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "suggestion", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Suggestion suggestion);

    /**
     * 
     * @param suggestionId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteSuggestion", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.DeleteSuggestion")
    @ResponseWrapper(localName = "deleteSuggestionResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.DeleteSuggestionResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/deleteSuggestionRequest", output = "http://webservice.storage.knowyourtown/Storage/deleteSuggestionResponse")
    public int deleteSuggestion(
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId);

    /**
     * 
     * @param personId
     * @param title
     * @return
     *     returns knowyourtown.localdb.webservice.Suggestion
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestionByTitle", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSuggestionByTitle")
    @ResponseWrapper(localName = "getSuggestionByTitleResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetSuggestionByTitleResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getSuggestionByTitleRequest", output = "http://webservice.storage.knowyourtown/Storage/getSuggestionByTitleResponse")
    public Suggestion getSuggestionByTitle(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "title", targetNamespace = "")
        String title);

    /**
     * 
     * @param city
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "weather", targetNamespace = "")
    @RequestWrapper(localName = "getWeatherInformationByCity", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetWeatherInformationByCity")
    @ResponseWrapper(localName = "getWeatherInformationByCityResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetWeatherInformationByCityResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getWeatherInformationByCityRequest", output = "http://webservice.storage.knowyourtown/Storage/getWeatherInformationByCityResponse")
    public String getWeatherInformationByCity(
        @WebParam(name = "city", targetNamespace = "")
        String city);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "quote", targetNamespace = "")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetQuoteResponse")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getQuoteRequest", output = "http://webservice.storage.knowyourtown/Storage/getQuoteResponse")
    public String getQuote();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "quote2", targetNamespace = "")
    @RequestWrapper(localName = "getQuote2", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetQuote2")
    @ResponseWrapper(localName = "getQuote2Response", targetNamespace = "http://webservice.storage.knowyourtown/", className = "knowyourtown.storage.webservice.GetQuote2Response")
    @Action(input = "http://webservice.storage.knowyourtown/Storage/getQuote2Request", output = "http://webservice.storage.knowyourtown/Storage/getQuote2Response")
    public String getQuote2();

}
